<?php
/**
 *  Copyright © Aitoc. All rights reserved.
 */

/**  @var $block Aitoc\GoogleReviews\Block\Badge */
?>
<script src="https://apis.google.com/js/platform.js?onload=renderBadge" async defer></script>
<?php /* @phpstan-ignore-next-line */ ?>
<?php if ($block->getLanguage()): ?>
    <script>
        window.___gcfg = {
            <?php /* @phpstan-ignore-next-line */ ?>
            lang: "<?= /* @noEscape */ $block->getLanguage() ?>"
        };
    </script>
<?php endif; ?>

<script>
    window.renderBadge = function() {
        var ratingBadgeContainer = document.createElement("div");
        document.body.appendChild(ratingBadgeContainer);
        window.gapi.load('ratingbadge', function() {
            window.gapi.ratingbadge.render(
                ratingBadgeContainer, {
                    <?php /* @phpstan-ignore-next-line */ ?>
                    "merchant_id": <?= /* @noEscape */ $block->getMerchantId() ?>,
                    <?php /* @phpstan-ignore-next-line */ ?>
                    "position": "<?= /* @noEscape */ $block->getPosition() ?>"
                });
        });
    }
</script>