<?php
/**
 * Copyright © Aitoc, Inc. All rights reserved.
 */
?>

<?php
/* @phpstan-ignore-next-line */
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
/* @phpstan-ignore-next-line */
$_colspan = $block->isAddAfter() ? 2 : 1;
?>

<div class="design_theme_ua_regexp" id="grid<?= /* @noEscape */ $_htmlId; ?>">
    <div class="admin__control-table-wrapper" style="overflow: initial">
        <?php /* @phpstan-ignore-next-line */ ?>
        <table class="admin__control-table" id="<?= /* @noEscape */ $block->getElement()->getId() ?>">
            <thead>
            <tr>
                <?php /* @phpstan-ignore-next-line */ ?>
                <?php foreach ($block->getColumns() as $columnName => $column): ?>
                    <th><?= /* @noEscape */ $column['label']; ?></th>
                <?php endforeach;?>
                <th class="col-actions" colspan="<?= /* @noEscape */ $_colspan; ?>">Action</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <?php /* @phpstan-ignore-next-line */ ?>
                <td colspan="<?= count($block->getColumns())+$_colspan; ?>" class="col-actions-add">
                    <button id="addToEndBtn<?= /* @noEscape */ $_htmlId; ?>" class="action-add" title="<?= /* @noEscape */ __('Add'); ?>" type="button">
                        <span><?= /* @noEscape */ __('Add Delivery Time Rule'); ?></span>
                    </button>
                </td>
            </tr>
            </tfoot>
            <tbody id="addRow<?= /* @noEscape */ $_htmlId; ?>"></tbody>
        </table>
    </div>
    <?php /* @phpstan-ignore-next-line */ ?>
    <input type="hidden" name="<?= /* @noEscape */ $block->getElement()->getName(); ?>[__empty]" value="" />

    <script>
        require([
            'jquery',
            'mage/template',
            'prototype',
            'mage/translate',
            'Aitoc_GoogleReviews/js/chosen.proto.min'
        ], function (jQuery, mageTemplate) {

            // create row creator
            window.arrayRow<?= /* @noEscape */ $_htmlId ?> = {

                pleaseSelect: jQuery.mage.__('Select Options'),

                // define row prototypeJS template
                template: mageTemplate(
                   <?php // phpcs:ignore ?>
                    '<tr id="<%- _id %>">'
                    <?php /* @phpstan-ignore-next-line */ ?>
                    <?php foreach ($block->getColumns() as $columnName => $column): ?>
                    + '<td>'
                        <?php /* @phpstan-ignore-next-line */ ?>
                        + '<?= /* @noEscape */ $block->renderCellTemplate($columnName)?>'
                    + '<\/td>'
                    <?php endforeach; ?>
                    <?php /* @phpstan-ignore-next-line */ ?>
                    <?php if ($block->isAddAfter()): ?>
                    <?php // phpcs:ignore ?>
                    + '<td><button class="action-add" type="button" id="addAfterBtn<%- _id %>"><span><?= /* @noEscape */ __('Add after'); ?><\/span><\/button><\/td>'
                    <?php endif; ?>
                    <?php // phpcs:ignore ?>
                    + '<td class="col-actions"><button onclick="arrayRow<?= /* @noEscape */ $_htmlId ?>.del(\'<%- _id %>\')" class="action-delete" type="button"><span><?= /* @noEscape */ __('Delete'); ?><\/span><\/button><\/td>'
                    +'<\/tr>'
                ),

                add: function(rowData, insertAfterId) {
                    // generate default template data
                    var templateValues;

                    // Prepare template values
                    if (rowData) {
                        templateValues = rowData;
                    } else {
                        var d = new Date();
                        templateValues = {
                        <?php /* @phpstan-ignore-next-line */ ?>
                        <?php foreach ($block->getColumns() as $columnName => $column): ?>
                            <?= /* @noEscape */ $columnName ?>: '',
                            'option_extra_attrs': {},
                        <?php endforeach; ?>
                        _id: '_' + d.getTime() + '_' + d.getMilliseconds()
                    };
                    }

                    // Insert new row after specified row or at the bottom
                    if (insertAfterId) {
                        Element.insert($(insertAfterId), {after: this.template(templateValues)});
                    } else {
                        Element.insert($('addRow<?= /* @noEscape */ $_htmlId ?>'), {bottom: this.template(templateValues)});
                    }
                    var selects = $$('.admin__control-table select');

                    new Chosen(selects.last(), {
                        width: "230px",
                        placeholder_text: this.pleaseSelect
                    });
                    new Chosen(selects[selects.length - 2], {
                        width: "220px",
                        placeholder_text: this.pleaseSelect
                    });

                    // Fill controls with data
                    if (rowData) {
                        var rowInputElementNames = Object.keys(rowData.column_values);
                        for (var i = 0; i < rowInputElementNames.length; i++) {
                            if ($(rowInputElementNames[i])) {
                                $(rowInputElementNames[i]).value = rowData.column_values[rowInputElementNames[i]];
                            }
                        }
                    }

                    // Add event for {addAfterBtn} button
                    <?php /* @phpstan-ignore-next-line */ ?>
                    <?php if ($block->isAddAfter()): ?>
                    Event.observe('addAfterBtn' + templateValues._id, 'click', this.add.bind(this, false, templateValues._id));
                    <?php endif; ?>
                },

                del: function(rowId) {
                    $(rowId).remove();
                }
            }

            // bind add action to "Add" button in last row
            Event.observe('addToEndBtn<?= /* @noEscape */ $_htmlId ?>', 'click', arrayRow<?= /* @noEscape */ $_htmlId ?>.add.bind(arrayRow<?= /* @noEscape */ $_htmlId ?>, false, false));

            // add existing rows
            <?php
            /* @phpstan-ignore-next-line */
            foreach ($block->getArrayRows() as $_rowId => $_row) { ?>
                <?= /* @noEscape */ "arrayRow{$_htmlId}.add(" . $_row->toJson() . ");\n";
            }
            ?>

            // Toggle the grid availability, if element is disabled (depending on scope)
            <?php /* @phpstan-ignore-next-line */ ?>
            <?php if ($block->getElement()->getDisabled()):?>
            toggleValueElements({checked: true}, $('grid<?= /* @noEscape */ $_htmlId; ?>').parentNode);
            <?php endif;?>
        });
    </script>
</div>
